project:
  type: website
website:
  title: "Tutorials"
  navbar:
    logo: icons/bi-body-text.svg
    tools:
      - icon: github
        href: https://github.com/baharmon
    left:
      - href: index.qmd
        text: Home
      - design/index.qmd
      - grass/index.qmd
  sidebar:
    style: "floating"
    search: true
    contents: auto
format:
  html:
    theme:
      - theme.scss
      - brand
    css: styles.css
    toc: true
    csl: acm.csl



